name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Restore NuGet Packages
      run: |
        echo "Restoring NuGet packages..."
        nuget restore ${{ github.workspace }}/sunone_aimbot_cpp.sln
      shell: powershell

    - name: Build the Project
      run: |
        echo "Building the project using prebuilt OpenCV and Boost..."
        msbuild ${{ github.workspace }}/sunone_aimbot_cpp.sln /p:Configuration=Release /verbosity:minimal
      shell: powershell

    - name: Prepare Release Assets
      run: |
        mkdir -p ${{ github.workspace }}/release
        cp ${{ github.workspace }}/Release/ai.exe ${{ github.workspace }}/release
      shell: powershell

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.workspace }}/release/ai.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
