name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 1

    - name: Debug Repository Structure
      run: |
        echo "Listing repository contents..."
        Get-ChildItem -Recurse ${{ github.workspace }}
      shell: powershell

    - name: Restore NuGet Packages
      run: |
        nuget restore "${{ github.workspace }}\sunone_aimbot_cpp.sln"
      shell: powershell

    - name: Install Missing NuGet Package
      run: |
        echo "Installing missing NuGet package..."
        nuget install Microsoft.Windows.CppWinRT -Version 2.0.240405.15 -OutputDirectory ${{ github.workspace }}\packages
      shell: powershell

    - name: Build the Project
      run: |
        echo "Building the project with Visual Studio 2022 Build Tools..."
        msbuild "${{ github.workspace }}\sunone_aimbot_cpp.sln" /p:PlatformToolset=v143 /p:Configuration=Release /verbosity:minimal
      shell: powershell

    - name: Prepare Release Assets
      run: |
        mkdir -p ${{ github.workspace }}\release
        cp ${{ github.workspace }}\Release\ai.exe ${{ github.workspace }}\release
      shell: powershell

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.workspace }}\release\ai.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
